sudo: required
language: generic
services:
  - docker


before_install:
  - docker build -t fredtgv/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true fredtgv/docker-react npm run test
